name: latestTagUpdate
run-name: ${{ github.actor }} is updating the latest tag
on: 
  push:
    branches:
      - main

jobs:
  remove-latest-tag:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Removing the latest tag if it exists..."
#       - run: 

#   add-latest-tag:
