name: Re-tag last commit

on:
  push:
    branches:
      - main # Trigger on push to the main branch


jobs:
  retag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important: ensures full history and tags are available

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Remove old 'latest' tag from remote
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/latest$"; then
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} :refs/tags/latest
          else
            echo "No existing 'latest' tag found on remote."
          fi

      - name: Create 'latest' tag on current commit
        run: |
          git tag -f latest
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} --tags
